 
# -----------------------------------------------------------------------------------------------
#  Copyright (c) Red Hat, Inc. All rights reserved.
#  Licensed under the MIT License. See LICENSE file in the project root for license information.
# ----------------------------------------------------------------------------------------------- 

name: OpenShift VSTS CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node_version:
          - 14
          - 16
          - 20
        architecture:
          - x64
        #Legacy includes:
        include:
          - os: macos-latest
            node_version: 10
            architecture: arm64
          - os: ubuntu-latest
            node_version: 10
            architecture: x64
          - os: windows-latest
            node_version: 10
            architecture: x64
    name: Node ${{ matrix.node_version }} - ${{ matrix.architecture }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
          architecture: ${{ matrix.architecture }}
      - run: npm run setup
      - run: npm ci
      - run: npm run compile
      - run: npm test
